# Getting started in PyTorch!
Resources:
* Ground-truth notebook — https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb
* Book version — https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.12.0+cu130


# Tensors
## Tensors are created in pyTorch by using `torch.Tensor()`

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 7],
                       [7, 7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([7, 7])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 6]])

In [16]:
TENSOR[0][0][0]

tensor(1)

In [17]:
TENSOR[0][0].shape

torch.Size([3])

## Random Tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers → look at data → update random numbers look at data → update random numbers`

In [18]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(5, 5, 6)
random_tensor

tensor([[[0.3030, 0.5617, 0.5565, 0.0328, 0.3343, 0.7199],
         [0.5406, 0.7364, 0.7335, 0.4827, 0.1045, 0.5164],
         [0.1353, 0.7077, 0.4518, 0.6912, 0.2676, 0.3398],
         [0.6507, 0.6862, 0.7673, 0.2402, 0.6688, 0.9076],
         [0.1441, 0.8337, 0.0012, 0.0074, 0.7218, 0.2968]],

        [[0.8007, 0.4778, 0.4272, 0.3600, 0.4593, 0.4846],
         [0.3494, 0.4092, 0.9309, 0.6080, 0.0931, 0.3430],
         [0.0609, 0.4618, 0.8554, 0.0614, 0.9405, 0.8943],
         [0.5249, 0.1454, 0.1205, 0.4526, 0.7241, 0.1368],
         [0.4503, 0.9406, 0.5706, 0.6389, 0.9202, 0.8823]],

        [[0.9261, 0.3443, 0.5782, 0.9323, 0.8175, 0.5587],
         [0.1311, 0.5751, 0.3902, 0.2742, 0.5244, 0.0315],
         [0.3742, 0.9443, 0.5640, 0.3744, 0.8569, 0.2795],
         [0.0676, 0.4328, 0.9087, 0.8495, 0.8396, 0.2600],
         [0.8408, 0.4339, 0.8486, 0.6635, 0.2274, 0.5418]],

        [[0.4355, 0.5729, 0.3015, 0.7398, 0.4876, 0.2768],
         [0.8679, 0.2792, 0.2905, 0.5968, 0.7356, 

## Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

## Create a Range of tensors and tensors-like

In [22]:
# Use torch.arange()
strange_tensors = torch.arange(start=0, end= 1000, step=77)

In [23]:
# Use tensors-like
strange_ones = torch.ones_like(input=strange_tensors)
strange_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## PyTorch Datatypes
**Note:** Tensor datatypes are one of the three big errors you might run into with PyTorch and deep learning:
1. Tensors are not the right data type
2. Tensors are not the right shape
3. Tensors are not on the right device

In [24]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 7.0], # Even if datatype is set to None, datatype will still be float32
                               dtype=None,      # data type of the tensor
                               device=None,     # what device the tensor is on
                               requires_grad=False) # whether to track gradients
print(f"float_32_tensor = {float_32_tensor}"
      f"\nfloat_32_tensor.dtype = {float_32_tensor.dtype}")

float_32_tensor = tensor([3., 6., 7.])
float_32_tensor.dtype = torch.float32


In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
print(f"float_16_tensor = {float_16_tensor}")

float_16_tensor = tensor([3., 6., 7.], dtype=torch.float16)


In [26]:
unknown_tensor = float_32_tensor * float_16_tensor      # pytorch will automatically convert the datatype to the one with more information
print(f"unknown_tensor = {unknown_tensor}\nunknown_tensor.dtype = {unknown_tensor.dtype}")

unknown_tensor = tensor([ 9., 36., 49.])
unknown_tensor.dtype = torch.float32


In [27]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
print(f"int_32_tensor = {int_32_tensor}\nint_32_tensor.dtype = {int_32_tensor.dtype}")

int_32_tensor = tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor.dtype = torch.int32


## Getting information from a tensor (Tensor Attributes)
1. Tensors not the right data type - to get datatype of the tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape of the tensor, can use `tensor.shape`
3. Tensors not on the right device - to get `device` from a tensor, can use `tensor.device`

In [28]:
# Create a tensor
# some_tensor = torch.rand(3, 4).to("cuda") # This is not safe, instead do this:
# some_tensor = torch.rand(3, 4).to(torch.device("cuda"))
# or, set a device manually for safety
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
some_tensor = torch.rand(3, 4, device=device)
some_tensor

tensor([[0.4072, 0.3494, 0.4475, 0.2623],
        [0.7859, 0.9761, 0.2179, 0.8766],
        [0.5198, 0.4544, 0.7525, 0.5590]], device='cuda:0')

In [29]:
# Find some details about the tensor
print(f"Our tensor: {some_tensor}\n"
      f"Datatype: {some_tensor.dtype}\n"
      f"Shape: {some_tensor.shape}\n"
      f"Device: {some_tensor.device}")

Our tensor: tensor([[0.4072, 0.3494, 0.4475, 0.2623],
        [0.7859, 0.9761, 0.2179, 0.8766],
        [0.5198, 0.4544, 0.7525, 0.5590]], device='cuda:0')
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cuda:0


## Manipulating Tensors (Tensor Operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [30]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor - 10

tensor([-9, -8, -7])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [34]:
tensor  # original tensor remains same though

tensor([1, 2, 3])

Pytorch also has `torch.<operation>` syntax for the above operations, like :

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [36]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise Multiplication (Scalar Multiplication)
2. Matrix Multiplication

Check out the http://matrixmultiplication.xyz/ page for intuition on how **matrix multiplication** works.

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
    * `(3, 2) @ (2, 3)` won't work
    * `(2, 3) @ (3, 2)` will work
    * `(3, 2) @ (2, 3)` will work
2. The resulting matrix will have the shape of the **outer dimensions**
    * `(3, 2) @ (2, 3)` -> `(3, 3)`
    * `(2, 3) @ (3, 5)` -> `(2, 5)`

In [37]:
# Element-wise multiplication
print(f"{tensor} * {tensor}"
      f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])Equals: tensor([1, 4, 9])


In [38]:
# Matrix multiplication
print(f"Matrix Multiplication: {tensor} @ {tensor}"
      f" Equals: {torch.matmul(tensor, tensor)}")    # Can also use tensor @ tensor

Matrix Multiplication: tensor([1, 2, 3]) @ tensor([1, 2, 3]) Equals: 14


In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 269 μs


tensor(14)

In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 80.8 μs


tensor(14)

## One of the most common errors in deep learning: shape errors


In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can use a **transpose**.
A **transpose** switches the axes or shape of a given tensor.


In [42]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [43]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9,  9],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [44]:
print(f"Original shapes: tensor_A =  {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B = {tensor_B.T.shape}")
print("Result of matrix multiplication:")
output = torch.matmul(tensor_A, tensor_B.T)
print(f"Output = {output}"
      f"\nOutput shape = {output.shape}")

Original shapes: tensor_A =  torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])
Result of matrix multiplication:
Output = tensor([[ 23,  29,  33],
        [ 53,  67,  75],
        [ 83, 105, 117]])
Output shape = torch.Size([3, 3])


## Finding min, max, mean, sum, &c (tensor aggregation)

In [45]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

**Note:** the torch.mean() function requires a tensor of float32 datatype to work

## Finding the position regarding the min and the max element of a tensor

In [49]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
# Find the position in the tensor that has the minimum value with argmin()
# |-> returns index position of the target tensor where the minimum occurs
torch.argmin(x)

tensor(0)

In [51]:
# Find the position in the tensor that has the maximum value with argmax()
# |-> returns index position of the target tensor where the maximum occurs
torch.argmax(x)

tensor(9)

In [52]:
# This syntax may also be used
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping — reshapes an input tensor to a defined shape
* View — Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking — combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze — removes all `1` dimensions from a tensor
* Unsqueeze — add a `1` dimension to a target vector
* Permute — Return a view of the input with dimensions permuted (swapped) in a certain way.

In [53]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
y = torch.rand(2, 1, 2, 1, 2)
y, y.shape

(tensor([[[[[0.9010, 0.8579]],
 
           [[0.5335, 0.2257]]]],
 
 
 
         [[[[0.2697, 0.7819]],
 
           [[0.5502, 0.8549]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [59]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {y}"
      f"\nPrevious shape: {y.shape}")

Previous tensor: tensor([[[[[0.9010, 0.8579]],

          [[0.5335, 0.2257]]]],



        [[[[0.2697, 0.7819]],

          [[0.5502, 0.8549]]]]])
Previous shape: torch.Size([2, 1, 2, 1, 2])


In [60]:
y_squeezed = torch.squeeze(y)
print(f"New tensor: {y_squeezed}"
      f"\nNew shape: {y_squeezed.shape}")

New tensor: tensor([[[0.9010, 0.8579],
         [0.5335, 0.2257]],

        [[0.2697, 0.7819],
         [0.5502, 0.8549]]])
New shape: torch.Size([2, 2, 2])


In [61]:
# torch.unsqueeze() – adds a single dimension to a target tensor at a specific diam (dimension)
print(f"Previous target: {y_squeezed}"
      f"\nPrevious shape: {y_squeezed.shape}")
# Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
print(f"New tensor: {y_unsqueezed}"
      f"\nNew Shape: {y_unsqueezed.shape}")

Previous target: tensor([[[0.9010, 0.8579],
         [0.5335, 0.2257]],

        [[0.2697, 0.7819],
         [0.5502, 0.8549]]])
Previous shape: torch.Size([2, 2, 2])
New tensor: tensor([[[[0.9010, 0.8579],
          [0.5335, 0.2257]]],


        [[[0.2697, 0.7819],
          [0.5502, 0.8549]]]])
New Shape: torch.Size([2, 1, 2, 2])


In [68]:
# torch.permute() — rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}"
      f"\nNew shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [69]:
x_original[0, 0, 0] = 786
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(786.), tensor(786.))

## Indexing (selecting data from tensors)
Indexing in pytorch is similar to numPy

In [70]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
# Let's index on middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [77]:
# Let's index on the innermost bracket (last dimension)
x[0][1][1]

tensor(5)

In [80]:
# You can use ":" to target "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [81]:
# Get all the values of the 0th and 1st dimension, but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [82]:
# Get all the values of dimension 0 but only 1 index of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [83]:
x[0, 0, :]

tensor([1, 2, 3])

In [91]:
# Index on x to return 9
print(x[0, 2, 2])
# Index on x to return 3, 6, 9
print(x[0, :, 2])

tensor(9)
tensor([3, 6, 9])


## PyTorch and NumPy
NumPy is a popular scientific Python numerical library.
And because of this, PyTorch has functionality to react with it.
* Data in NumPy, want in PyTorch tensor → `torch.from_numpy(ndarray)`
* PyTorch tensor → NumPy → `torch.Tensor.numpy()`
### NumPy Array to Tensor

In [1]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [2]:
# Default data type for numpy float array
array.dtype

dtype('float64')

In [3]:
# Default data type for a float tensor in pytorch
torch.arange(1.0, 8.0).dtype

torch.float32

**WARNING:** When converting from NumPy → PyTorch, PyTorch reflects NumPy's default datatype of float64 unless specified otherwise: like,
`tensor = torch.from_numpy(array).type(tortch.float32)`.
Now if we change the value of `array`, what will this do to `tensor`?

In [4]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

As seen above, the pytorch tensor is created in memory when using from_numpy(), so its value does not change
### Tensor to NumPy Array

In [5]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [6]:
numpy_tensor.dtype

dtype('float32')

**WARNING:** Default value of PyTorch is reflected in NumPy array as `float32`, when converting from PyTorch → NumPy.
Now, if we change `tensor`, what change will happen to `numpy_tensor`?

In [7]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of randomness)
In short, how a neural network learns:
`start with random numbers → tensor operations → update random numbers to try and make them better representations of data
→ again, again and, again...`

To reduce the randomness in neural networks and pytorch, comes the concept of **random seeds.**
Essentially, what the random seed does is that it adds "flavour" to the randomness.

In [8]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"random_tensor_A : {random_tensor_A}")
print(f"random_tensor_B : {random_tensor_B}")
print(random_tensor_A == random_tensor_B)

random_tensor_A : tensor([[0.8833, 0.0195, 0.1678, 0.7652],
        [0.1017, 0.3732, 0.8761, 0.8975],
        [0.7121, 0.5922, 0.7659, 0.2047]])
random_tensor_B : tensor([[0.6153, 0.3246, 0.9562, 0.4926],
        [0.6216, 0.6977, 0.0831, 0.1107],
        [0.6649, 0.3360, 0.4063, 0.8756]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [10]:
# Let's make some random but reproducible tensors
import torch
# Set the random seed
RANDOM_STATE = 42
torch.manual_seed(RANDOM_STATE)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_STATE)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In pytorch, you have to set the random seed everytime you call the `rand` function.

**Extra** resources for **reproducibility**:
* https://docs.pytorch.org/docs/2.12/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Accessing the GPU
GPU = Faster computation in numbers, thanks to CUDA + NVIDIA Hardware + PyTorch working in the background to make everything hunky-dory.
### How to get a GPU?
1. Easiest - Use Google colab.
2. Install CUDA + PyTorch on your own machine with NVIDIA GPU.
3. Use Cloud computing services like Azure, AWS, GCP...

For 2, 3 you need to set up GPU drivers (CUDA). For more information, refer to: https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Tue Jun 23 02:01:46 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.62                 KMD Version: 610.62        CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5070 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   45C    P0             12W /  115W |    2412MiB /   8151MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access for PyTorch

In [14]:
# To check for GPU access in pytorch
import torch
torch.cuda.is_available()

True

Since PyTorch can run on both a GPU or a CPU, curate/customize your code to be device-agnostic, meaning:
use a GPU if available, otherwise default to a CPU. For more information, refer to: https://docs.pytorch.org/docs/2.12/notes/cuda.html#best-practices

In [15]:
# Set up device-agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [17]:
# Check the number of GPUs
torch.cuda.device_count()

1

### Putting tensors (and models on the GPU)
The reason we want to put our tensors on a GPU is that using a GPU results in faster computation.

In [24]:
# Create a tensor (default is on the CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)    # tensor not on gpu
# Move the tensor to the GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


### Putting tensors back to the CPU

In [28]:
# If tensor is on GPU, can't transform it to numpy
try:
    tensor_on_gpu.numpy()
except Exception as e:
    print(f"Error Type: {type(e).__name__} | Message: {e}")

Error Type: TypeError | Message: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


In [31]:
# To fix the GPU tensor with the NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_back_on_cpu.device

(array([1, 2, 3]), 'cpu')

# Exercises and Extra-curriculum
See exercises and extra curriculum here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises