<a href="https://colab.research.google.com/github/DinoKiller0607/My_Pytorch_Notes/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started in PyTorch!

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.12.0+cu130


# Tensors
### Tensors are created in pyTorch by using `torch.Tensor()`

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 7],
                       [7, 7]])
MATRIX

tensor([[7, 7],
        [7, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([7, 7])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 4, 6]])

In [ ]:
TENSOR[0][0][0]

tensor(1)

In [ ]:
TENSOR[0][0].shape

torch.Size([3])

### Random Tensors
Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers → look at data → update random numbers look at data → update random numbers`

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(5, 5, 6)
random_tensor

tensor([[[0.5898, 0.4249, 0.3312, 0.7558, 0.4874, 0.6542],
         [0.8407, 0.3216, 0.8370, 0.0105, 0.1245, 0.0405],
         [0.8023, 0.0653, 0.3379, 0.3510, 0.8747, 0.7344],
         [0.8300, 0.1891, 0.7875, 0.9926, 0.3824, 0.5753],
         [0.4706, 0.6172, 0.0528, 0.8751, 0.8726, 0.5075]],

        [[0.3687, 0.5092, 0.9239, 0.3241, 0.3397, 0.1390],
         [0.3179, 0.0962, 0.3231, 0.9836, 0.2246, 0.3542],
         [0.3872, 0.4841, 0.4250, 0.4707, 0.6733, 0.0298],
         [0.5716, 0.1232, 0.8333, 0.5165, 0.1529, 0.5164],
         [0.1038, 0.4060, 0.0768, 0.8094, 0.0608, 0.5556]],

        [[0.5368, 0.2417, 0.0812, 0.2553, 0.4303, 0.6287],
         [0.2069, 0.8223, 0.1086, 0.0502, 0.4156, 0.1587],
         [0.6284, 0.8463, 0.4765, 0.9899, 0.3927, 0.7013],
         [0.3119, 0.6334, 0.9980, 0.2465, 0.0723, 0.8214],
         [0.4287, 0.9647, 0.8971, 0.1008, 0.9336, 0.2943]],

        [[0.9535, 0.4841, 0.8585, 0.1169, 0.7284, 0.6376],
         [0.9174, 0.6942, 0.4302, 0.0968, 0.2730, 

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a Range of tensors and tensors-like

In [ ]:
# Use torch.arange()
strange_tensors = torch.arange(start=0, end= 1000, step=77)

In [ ]:
# Use tensors-like
strange_ones = torch.ones_like(input=strange_tensors)
strange_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### PyTorch Datatypes
**Note:** Tensor datatypes is one of the three big errors you might run into with PyTorch and deep learning:
1. Tensors not the right data type
2. Tensors not the right shape
3. Tensors not on the right device

In [ ]:
# Float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 7.0], # Even if datatype is set to None, datatype will still be float32
                               dtype=None,      # data type of the tensor
                               device=None,     # what device the tensor is on
                               requires_grad=False) # whether to track gradients
print(f"float_32_tensor = {float_32_tensor}"
      f"\nfloat_32_tensor.dtype = {float_32_tensor.dtype}")

float_32_tensor = tensor([3., 6., 7.])
float_32_tensor.dtype = torch.float32


In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
print(f"float_16_tensor = {float_16_tensor}")

float_16_tensor = tensor([3., 6., 7.], dtype=torch.float16)


In [ ]:
unknown_tensor = float_32_tensor * float_16_tensor      # pytorch will automatically convert the datatype to the one with more information
print(f"unknown_tensor = {unknown_tensor}\nunknown_tensor.dtype = {unknown_tensor.dtype}")

unknown_tensor = tensor([ 9., 36., 49.])
unknown_tensor.dtype = torch.float32


In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
print(f"int_32_tensor = {int_32_tensor}\nint_32_tensor.dtype = {int_32_tensor.dtype}")

int_32_tensor = tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor.dtype = torch.int32


### Getting information from a tensor (Tensor Attributes)
1. Tensors not the right data type - to get datatype of the tensor, can use `tensor.dtype`
2. Tensors not the right shape - to get shape of the tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
# some_tensor = torch.rand(3, 4).to("cuda") # This is not safe, instead do this:
# some_tensor = torch.rand(3, 4).to(torch.device("cuda"))
# or, set a device manually for safety
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
some_tensor = torch.rand(3, 4, device=device)
some_tensor

tensor([[0.6546, 0.7642, 0.3395, 0.4355],
        [0.6446, 0.0875, 0.0745, 0.3355],
        [0.6957, 0.7534, 0.7903, 0.5957]], device='cuda:0')

In [ ]:
# Find some details about the tensor
print(f"Our tensor: {some_tensor}\n"
      f"Datatype: {some_tensor.dtype}\n"
      f"Shape: {some_tensor.shape}\n"
      f"Device: {some_tensor.device}")

Our tensor: tensor([[0.6546, 0.7642, 0.3395, 0.4355],
        [0.6446, 0.0875, 0.0745, 0.3355],
        [0.6957, 0.7534, 0.7903, 0.5957]], device='cuda:0')
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cuda:0


### Manipulating Tensors (Tensor Operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor  # original tensor remains same though

tensor([1, 2, 3])

Pytorch also has `torch.<operation>` syntax for above operations, like :

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise Multiplication (Scalar Multiplication)
2. Matrix Multiplication

Check out the `matrixmultiplication.xyz` page for intuition on how **matrix multiplication** works.

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (2, 3)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix will have the shape of the **outer dimensions**
* `(3, 2) @ (2, 3)` -> `(3, 3)`
* `(2, 3) @ (3, 5)` -> `(2, 5)`

In [ ]:
# Element-wise multiplication
print(f"{tensor} * {tensor}"
      f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
print(f"Matrix Multiplication: {tensor} @ {tensor}"
      f" Equals: {torch.matmul(tensor, tensor)}")    # Can also use tensor @ tensor

Matrix Multiplication: tensor([1, 2, 3]) @ tensor([1, 2, 3]) Equals: 14


In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 223 μs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 68.7 μs


tensor(14)

### One of the most common errors in deep learning: shape errors


In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [9, 12]])
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can use a **transpose**.
A **transpose** switches the axes or shape of a given tensor.


In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9,  9],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
print(f"Original shapes: tensor_A =  {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B = {tensor_B.T.shape}")
print("Result of matrix multiplication:")
output = torch.matmul(tensor_A, tensor_B.T)
print(f"Output = {output}"
      f"\nOutput shape = {output.shape}")

Original shapes: tensor_A =  torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])
Result of matrix multiplication:
Output = tensor([[ 23,  29,  33],
        [ 53,  67,  75],
        [ 83, 105, 117]])
Output shape = torch.Size([3, 3])


### Finding min, max, mean, sum, &c (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

**Note:** the torch.mean() function requires a tensor of float32 datatype to work

### Finding the position of the min and the max element of a tensor

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in the tensor that has the minimum value with argmin()
# |-> returns index position of target tensor where the minimum occurs
torch.argmin(x)

tensor(0)

In [ ]:
# Find the position in the tensor that has the maximum value with argmax()
# |-> returns index position of target tensor where the maximum occurs
torch.argmax(x)

tensor(9)

In [ ]:
# This syntax may also be used
x.argmin(), x.argmax()

(tensor(0), tensor(9))

### Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping — reshapes an input tensor to a defined shape
* View — Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking — combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze — removes all `1` dimensions from a tensor
* Unsqueeze — add a `1` dimension to a target vector
* Permute — Return a view of the input with dimensions permuted (swapped) in a certain way.

In [1]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [2]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [3]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [5]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [6]:
y = torch.rand(2, 1, 2, 1, 2)
y, y.shape

(tensor([[[[[0.8258, 0.1885]],
 
           [[0.6493, 0.3031]]]],
 
 
 
         [[[[0.4512, 0.0153]],
 
           [[0.1409, 0.7407]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [7]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {y}"
      f"\nPrevious shape: {y.shape}")

Previous tensor: tensor([[[[[0.8258, 0.1885]],

          [[0.6493, 0.3031]]]],



        [[[[0.4512, 0.0153]],

          [[0.1409, 0.7407]]]]])
Previous shape: torch.Size([2, 1, 2, 1, 2])


In [8]:
y_squeezed = torch.squeeze(y)
print(f"New tensor: {y_squeezed}"
      f"\nNew shape: {y_squeezed.shape}")

New tensor: tensor([[[0.8258, 0.1885],
         [0.6493, 0.3031]],

        [[0.4512, 0.0153],
         [0.1409, 0.7407]]])
New shape: torch.Size([2, 2, 2])


In [9]:
# torch.unsqueeze() – adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {y_squeezed}"
      f"\nPrevious shape: {y_squeezed.shape}")
# Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=1)
print(f"New tensor: {y_unsqueezed}"
      f"\nNew Shape: {y_unsqueezed.shape}")

Previous target: tensor([[[0.8258, 0.1885],
         [0.6493, 0.3031]],

        [[0.4512, 0.0153],
         [0.1409, 0.7407]]])
Previous shape: torch.Size([2, 2, 2])
New tensor: tensor([[[[0.8258, 0.1885],
          [0.6493, 0.3031]]],


        [[[0.4512, 0.0153],
          [0.1409, 0.7407]]]])
New Shape: torch.Size([2, 1, 2, 2])


In [10]:
# torch.permute() — rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}"
      f"\nNew shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [10]:
torc